### ISSUE TITLE
Why is the result of catSeqTG much lower than TG-net?

### ISSUE THREAD

**Issue by fredia** [kenchan0226/keyphrase-generation-rl#12]
The authors of TG-net report their results as follows：
![image](https://user-images.githubusercontent.com/18653940/78213265-bec26d80-74e4-11ea-941d-e58c4fefb670.png)
But  catSeqTG's results are much lower than what they report：
![image](https://user-images.githubusercontent.com/18653940/78213218-95a1dd00-74e4-11ea-903f-96702cafa533.png)

**Comment by kenchan0226** [comment]
Hi, because we are considering two different settings. Our setting requires a model to determine the number of keyphrases to generated for a given document, while the original TG-net paper considers a setting that a model produces a fixed number of keyphrases. Our setting is more difficult so the results are lower than the original TG-net paper.

**Comment by fredia** [comment]
hi, thank you for replying to my stupid question. It was my fault that I ignored the difference between F1@5 in your paper and others. Thank you for your code,it helped me a lot.
