### ISSUE TITLE
Using Pre-trained embedding

### ISSUE THREAD

**Issue by Xiao0728** [kenchan0226/keyphrase-generation-rl#15]
Hi, Kenchan,
I used the following command to use the pre-trained embedding to train the model, could you help me to check if it is right to use?
I have generated the Glove pretrained embedding, then when I submitted to train a catseq ML model using this cmd 
```
python3 train.py -data data/kp20k/ -vocab data/kp20k/ -pre_word_vecs_enc "data/kp20k/embeddings.enc.pt" -pre_word_vecs_dec "data/kp20k/embeddings.dec.pt" 
-exp_path exp/%s.%s -exp kp20k -epochs 20 -copy_attention -train_ml -one2many -one2many_mode 1 -batch_size 12 -separate_present_absent -seed 9527
```
Question1: I was wondering, since we have designated the `-pre_word_vecs_enc` and `-pre_word_vecs_dec`, why there still needs to specify the dataset path`-data` ? 

Question2: I'm kind of confused about whether RL training based on the ML pre-trained model needs to specify the options: `-pre_word_vecs_enc` and `-pre_word_vecs_dec`.

Thanks in advance.
Xiao

**Comment by kenchan0226** [comment]
The command is overall correct, but I think you still need to verify it by yourself because I did not use the pretrained embeddings in my paper so I did not spend lots of time to verify this part.
Question 1: because we still need to load the training samples from the path specify by -data. 
Question 2: I think for RL training, you don't need to specify `pre-word_vecs_enc` and `pre-word_vecs_dec` again, since they will load every parameters from a ml-pretrianed model.
