### ISSUE TITLE
how to generate present keyphrase only?

### ISSUE THREAD

**Issue by crystal0913** [kenchan0226/keyphrase-generation-rl#7]
I want to the model generate present keyphrases only, not generate absent keyphrase.
Is there a config or how can i change the code?

**Comment by kenchan0226** [comment]
Hi crystal, sorry, there is no configuration to generate present keyphrases only since our work focus on generating both present and absent keyphrases. Maybe you can set the `-topk` option during the reinforcement learning to `-topk M`. Then it will use the F1 score as the reward function instead of our RF1 reward, then the model will generate very little absent keyphrases. You can also add a preprocessing step to remove the absent keyphrases. Thanks.

**Comment by crystal0913** [comment]
thanks
